name: Static analysis

on: [push, pull_request]

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
    - name: Cache .git
      uses: actions/cache@v3
      with:
        path: ./.git
        key: git-dir-${{ github.job }}
    - uses: actions/checkout@v4
    - uses: DoozyX/clang-format-lint-action@v0.18.2
      with:
        source: '.'
  python-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Cache .git
      uses: actions/cache@v3
      with:
        path: ./.git
        key: git-dir-${{ github.job }}
    - uses: actions/checkout@v4
    - name: Setup environment
      run: |
        python3 -m pip install flake8
    - name: Run linter
      run: |
        python3 -m flake8 .
